### ISSUE TITLE
seems not working?

### ISSUE THREAD

**Issue by towry** [ColinKennedy/nvim-checkhealth-gh-action#4]
https://github.com/towry/nvim-astro/actions/runs/13985471108/job/39158287670?pr=31

```

Configuration ~
- WARNING Missing user config file: /Users/runner/.config/nvim/init.lua
  - ADVICE:
    - :help |config|
```

The workflow file copied from your nvim config. https://github.com/towry/nvim-astro/pull/31/files#diff-bf0a332cb146906dd89fd94ad8accbbe2d3fde63b64e96d7988b2187a66e5fbb

**Comment by ColinKennedy** [comment]
Thank you for bringing this to my attention.

The short answer to solve your immediate problem is to use this, I think:

```yml
      - name: Run :checkhealth
        uses: ColinKennedy/nvim-checkhealth-gh-action@v1.0.0
        with:
          executable: "nvim -u init.lua"
```

There's a cleaner way to solve the issue, see the explanation below:


## Explanation
In short, my example .yml / documentation is wrong and needs to be updated. The GitHub action is working but this repository isn't being cloned in the right spot. It's only noticeable in Neovim nightly I think because that check doesn't exist in previous Neovim versions.

Instead of adding `executable: "nvim -u init.lua"`, another solution would be to clone nvim-astro to `/Users/runner/.config/nvim`. Something like

```yml
      - name: Checkout code
        uses: actions/checkout@v4
```

Becomes

```yml
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: .config/nvim
```


And then there's no need to modify the `executable` parameter. Please try these options out and let me know

**Comment by ColinKennedy** [comment]
Update:

I tried a variety of methods. @towry please let me know if either of these work for you. The two best ways I found are:

## The "Just do it" Method
Hacky but works

```yml
      - name: Run :checkhealth
        uses: ColinKennedy/nvim-checkhealth-gh-action@main
        with:
          executable: "nvim -u init.lua"
```

## The "Do it right" Method
You'll need to tell Neovim where to look for your `init.lua` configuration file. Things get tricky because Neovim looks in `$XDG_CONFIG_HOME` but GitHub action runners aren't meant to touch that directory directly.

In short it can be simulated with:

```yml
    ...

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: nvim

      ...

      - name: Run :checkhealth
        env:
          XDG_CONFIG_HOME: ${{ github.workspace }}
        uses: ColinKennedy/nvim-checkhealth-gh-action@main
```

Assuming your repository has a `init.lua` in the root directory (which common in basically any Neovim configuration) then the above will create a `$XDG_CONFIG_HOME/nvim/init.lua` in the right place and instruct Neovim to look for the file there. I confirmed that it works in Linux, MacOS, and Windows.
